RESULTS_PARSER:
    TABLENAME_LOTS: "Перечень закупаемых товаров, работ, услуг на общую сумму"
    TABLENAME_PARTICIPANTS: "Информация о представленных заявках на участие в конкурсе"
    TABLENAME_SCORE_CALCULATION: "Информация о результатах применения относительного значения критериев, предусмотренных при равенстве"
    TABLENAME_RESULTS: "Расчет условных цен участников конкурса"
    COLNAME_LOTNUMBER: "№ лота"

    COMPONENTS: {   
        name: "Наименование потенциального поставщика",
        b_id: "БИН (ИИН)",
        experience_level: "Опыт работы за последние десять лет, предшествующих текущему году",
        tax_score: "Показатель уплаченных налогов",
        location_score: "Нахождение потенциального поставщика в соответствующей",
        negative_score: "Отрицательные значения за наличие у потенциального поставщика на исполнении договора о государственных закупках",
        score: "Общая условная скидка, %",
        bid: "Цена поставщика",
        score_bid: "Цена с учетом условной скидки",
        fin_stability: "Показатель финансовой устойчивости",
        applied_time: "Дата и время подачи заявки"
    }

    TESTS:
    - { name: "Test 1",
        tendername: "Строительство наружных сетей водопровода и канализации по адресу: микрорайон Рахат-Мадениет, Алатауского района, города Алматы» для КГУ «Аппарат акима Алатауского района города Алматы",
        filename: buy_pi_0624_0934_10079496.html, 
        link: https://ows.goszakup.gov.kz/download/trd_buy/68d5686d543be06d905c9aa4d315856c }
    - { name: "Test 2",
        tendername: "Строительство сквера по ул.Ибрагимова в мкр. Алатау» для КГУ «Аппарат акима Медеуского района города Алматы",
        filename: buy_pi_0620_1200_10087943.html, 
        link: https://ows.goszakup.gov.kz/download/trd_buy/d65c2ac43fb5e032ad96498fcb9637ff}
    - { name: "Test 3",
        tendername: "Реконструкция сквера журналистов» для КГУ «Аппарат акима Медеуского района города Алматы",
        filename: buy_pi_0620_1200_10088055.html, 
        link: https://ows.goszakup.gov.kz/download/trd_buy/e1875be88a05cc4b7e186a754b4131c3}
    - { name: "Test 4",
        tendername: "Реконструкция здания по улице Рихарда Зорге, дом 2 в Турксибском районе города Алматы» для КГУ «Аппарат акима Турксибского района города Алматы",
        filename: buy_pi_0614_0934_10098851.html,
        link: https://ows.goszakup.gov.kz/download/trd_buy/5d3fa6b19ccf2b602f1f233b344053f4}
    - { name: "Test 5",
        tendername: "Разработка ПСД «Реконструкция с пристройкой к зданию  РГКП «Государственный академический русский театр для детей и юношества имени Н. Сац», по адресу: мкр. 12, Ауэзовский район, города Алматы» для  КГУ «Управление строительства города Алматы",
        filename: buy_pi_0627_0933_10131093.html,
        link: https://ows.goszakup.gov.kz/download/trd_buy/43862c36e065f6c6c8d8e54ab2c1dbe5}
    - { name: "Test 6",
        tendername: "Электроснабжение 19 котельных города Алматы» для КГУ «Управление энергетики и водоснабжения города Алматы",
        filename: buy_pi_0627_0918_10131872.html,
        link: https://ows.goszakup.gov.kz/download/trd_buy/abe3ca1fde7e571aad477d93561ef49d}
    - { name: "Test 7",
        tendername: "Работы по возведению (строительству) нежилых зданий/сооружений",
        filename: buy_pi_0712_0918_10226863.html,
        link: https://ows.goszakup.gov.kz/download/trd_buy/79d9ae91ff108bf8536911c92773c7d6}


GRAPHQL_PARSER:
    WHOAMI: "GRAPHQL_PARSER"
    LOG_LEVEL_CONFIGHANDLER: "DEBUG"

    QUERIES:
        TRDBUY: "query($filter: TrdBuyFiltersInput, $after: Int) { ${TRDBUY} }"
        LOTS: "query($filter: LotsFiltersInput, $after: Int) { ${LOTS} }"

    OBJECTS:
        TRDBUY:
            NAME: "TrdBuy"
            RESTRICTIONS:
                LOTS: True
                FILES: True
                REFTRADEMETHODS: True
                REFSUBJECTTYPE: True
                REFBUYSTATUS: True
            QUERY: |
                TrdBuy(filter: $filter, after: $after) {
                    id
                    numberAnno
                    nameRu
                    nameKz
                    totalSum
                    refTradeMethodsId
                    orgBin
                    orgNameRu
                    startDate
                    endDate
                    publishDate
                    itogiDatePublic
                    biinSupplier
                    isConstructionWork
                    finYear
                    kato
                    ${LOTS}
                    ${FILES}
                    ${REFTRADEMETHODS}
                    ${REFSUBJECTTYPE}
                    ${REFBUYSTATUS}
                }

        LOTS:
            NAME: "Lots"
            RESTRICTIONS:
                PARTICIPANTS: True
            QUERY: |
                Lots {
                    id
                    lotNumber
                    refLotStatusId
                    count
                    amount
                    nameRu
                    nameKz
                    descriptionRu
                    descriptionKz
                    isConstructionWork
                    ${CUSTOMER}
                    ${REFLOTSTATUS}
                    ${FILES}
                }

        FILES:
            NAME: "Files"
            QUERY: "Files { filePath originalName nameRu }"

        CUSTOMER:
            NAME: "Customer"
            RESTRICTIONS:
                ADDRESS: True
            QUERY: "Customer { bin nameRu ${ADDRESS} }"

        ADDRESS:
            NAME: "Address"
            QUERY: "Address { id address katoCode }"

        REFTRADEMETHODS:
            NAME: "RefTradeMethods"
            QUERY: "RefTradeMethods { id nameRu code symbolCode }"

        REFSUBJECTTYPE:
            NAME: "RefSubjectType"
            QUERY: "RefSubjectType { id nameRu }"

        REFBUYSTATUS:
            NAME: "RefBuyStatus"
            QUERY: "RefBuyStatus { id nameRu code }"

        REFLOTSTATUS:
            NAME: "RefLotsStatus"
            QUERY: "RefLotsStatus { id nameRu code }"

    FILTERS:
        TRDBUY:
            "refSubjectTypeId": 2,    
            "refTradeMethodsId": 188,
            "refBuyStatusId": 350,
            "kato": ${KATO},
            "finYear": 2023,
            "totalSum": 200000000,  # 200 million

    INPUTS:
        KATO:
            ALMATY_REGION:
            - 191000000 # Қонаев Г.А.
            - 191600000 # Капчагай Г.А.
            - 192600000 # Текели Г.А.
            - 193200000 # Аксуский район
            - 193400000 # Алакольский район
            - 193600000 # Балхашский район
            - 194000000 # Енбекшиказахский район
            - 194200000 # Жамбылский район
            - 194400000 # Кегенский район
            - 194600000 # Кербулакский район
            - 194800000 # Коксуский район
            - 195000000 # Каратальский район
            - 195200000 # Карасайский район
            - 195600000 # Панфиловский район
            - 195800000 # Райымбекский район
            - 196000000 # Саркандский район
            - 196200000 # Талгарский район
            - 196400000 # Ескельдинский район
            - 196600000 # Уйгурский район
            - 196800000 # Илийский район

            ZHETISU_REGION:
            - 331000000 # Талдыкорган Г.А.
            - 331800000 # Текели Г.А.
            - 333200000 # Аксуский район
            - 333400000 # Алакольский район
            - 333600000 # Ескельдинский район
            - 334000000 # Кербулакский район
            - 334200000 # Коксуский район
            - 334400000 # Каратальский район
            - 334600000 # Панфиловский район
            - 334800000 # Саркандский район

            ALMATY_CITY:
            - 751110000 # Алмалинский район
            - 751210000 # Алатауский район
            - 751310000 # Ауэзовский район
            - 751410000 # Бостандыкский район
            - 751510000 # Жетысуский район
            - 751710000 # Медеуский район
            - 751810000 # Наурызбайский район
            - 751910000 # Турксибский район

        REF_LOTS_STATUS_VALUES:
            - {"id": 190, "nameRu": "Изменена документация", "code": "DocumentationСhanged" }
            - {"id": 210, "nameRu": "Опубликовано", "code": "Published" }
            - {"id": 220, "nameRu": "Опубликовано (прием заявок) ", "code": "PublishedOrderTaking" }
            - {"id": 230, "nameRu": "Опубликовано (дополнение заявок)", "code": "PublishedAdditionDemands" }
            - {"id": 240, "nameRu": "Опубликовано (прием ценовых предложений)", "code": "PublishedPriceOffers" }
            - {"id": 250, "nameRu": "Рассмотрение заявок", "code": "BidReview" }
            - {"id": 260, "nameRu": "Рассмотрение дополнений заявок", "code": "BidAdditionalReview" }
            - {"id": 349, "nameRu": "Завершено (период обжалования)", "code": "CompleteOnHold"}
            - {"id": 350, "nameRu": "Завершено", "code": "Complete" }
            - {"id": 410, "nameRu": "Отказ от закупки", "code": "RefusalOfPurchase" }
            - {"id": 430, "nameRu": "Отменено", "code": "Canceled" }
            - {"id": 440, "nameRu": "На обжаловании", "code": "OnAppellation" }
            - {"id": 540, "nameRu": "Принятие решение об исполнении уведомления", "code": "BeforeReviwePI" }

        REF_TRADE_METHODS_VALUES: 
            - {'id': 2, 'nameRu': 'Открытый конкурс'}
            - {"id": 3, "nameRu": "Запрос ценовых предложений"},
            - {"id": 6, "nameRu": "Из одного источника по несостоявшимся закупкам"}
            - {"id": 32, "nameRu": "Конкурс с предварительным квалификационным отбором"},
            - {"id": 132, "nameRu": "Первый этап конкурса с использованием рамочного соглашения"},
            - {'id': 188, 'nameRu': 'Конкурс с использованием рейтингово-балльной системы'}

        REF_SUBJECT_TYPE_VALUES:
            - {"id": 1, "nameRu": "Товар"}
            - {"id": 2, "nameRu": "Работа"}
            - {"id": 3, "nameRu": "Услуга"}


PRACTICE_TESTS:
    TEST_BOOL:
        BIG_TRUE: True
        SMALL_TRUE: true
        BIG_FALSE: False
        SMALL_FALSE: false