# config.yml

PARSEFILE:
  TEST:
    - {name: appendix_5_2022_263784.pdf, url: "https://ows.goszakup.gov.kz/download/trd_buy_lots_list/5698b9ff25b6a581fd4136d6d709ea45"}
    - {name: appendix_5_2022_10087943.pdf, url: "https://ows.goszakup.gov.kz/download/trd_buy_lots_list/fab16d47fb8e78c78c2229117fdd8ba0"}
    - {name: appendix_5_2022_10088055.pdf, url: "https://ows.goszakup.gov.kz/download/trd_buy_lots_list/cb651dfcb68cedc631ba752cef8f3345"}
    - {name: appendix_5_2022_10098851.pdf, url: "https://ows.goszakup.gov.kz/download/trd_buy_lots_list/62da9d34bbf04793647834896c33683c"}
    - {name: appendix_5_2022_268593.pdf, url: "https://ows.goszakup.gov.kz/download/trd_buy_lots_list/4d3cd9408333ab2c1b06773841d67840"}
    - {name: appendix_5_2022_10143145.pdf, url: "https://ows.goszakup.gov.kz/download/trd_buy_lots_list/4edf9092801613c9ee6d401fff91d954"}
    - {name: appendix_5_2022_10211410.pdf, url: "https://ows.goszakup.gov.kz/download/trd_buy_lots_list/d0c6dc7399d45b7fcb769daaab82bfb1"}
    - {name: appendix_5_2022_10226863.pdf, url: "https://ows.goszakup.gov.kz/download/trd_buy_lots_list/b40f97716797e3af2883f23d2f25638e"}
    - {name: appendix_5_2022_282953.pdf, url: "https://ows.goszakup.gov.kz/download/trd_buy_lots_list/8584debc05d7b3f0e468e9f6b5cfe6e2"}




RETRIEVETEXT:
  SPACE: "[\\s\\S]{0,5}"


PARSETEXT:
  TEST:
    TEST1: {name: Test level existence, test: "второй[\\s\\S]{0,5}нормальный", error: not found}
    TEST2: {name: Test type existence, test: "новое[\\s\\S]{0,5}строительство", error: not found}
    TEST3: {name: Test complexity existence, test: "относящиеся[\\s\\S]{0,5}к[\\s\\S]{0,5}технически", error: Technical not found}
    TEST4: {name: Test goal existence, test: "объекты[\\s\\S]{0,5}жилищно", error: not found}

  CHARACTERISTICS:
    TECHNICAL_COMPLEXITY:
      NAME: "technical_complexity"
      NAME_EN: Technical Complexity
      NAME_RU: Техническая сложность объектов
      CATEGORIES:
        - здания и сооружения, относящиеся к технически сложным объектам
        - здания и сооружения, не относящиеся к технически сложным объектам
    
    FUNCTIONAL_PURPOSE:
      NAME: "functional_purpose"
      NAME_EN: Functional purpose
      NAME_RU: Функциональное назначение
      CATEGORIES:
        - промышленные объекты
        - производственные здания
        - сооружения
        - объекты жилищно - гражданского назначения
        - прочие сооружения
    
    RESPONSIBILITY_LEVEL:
      NAME: "responsibility_level"
      NAME_EN: Responsibility level
      NAME_RU: Уровень ответственности зданий и сооружений
      CATEGORIES:
        - первый – повышенный
        - второй – нормальный
        - третий – пониженный

    TYPE_CONSTRUCTION:
      NAME: "type_construction"
      NAME_EN: Type of construction
      NAME_RU: Вид строительства
      CATEGORIES:
        - новое строительство
        - расширение
        - техническое перевооружение
        - модернизация
        - реконструкция
        - реставрация и капитальный ремонт существующих объектов

  THRESHOLD: 0.99